/**
 * Selector corpus for the ground-truth test of src/selector-grammar.ts.
 *
 * No expected outcome is recorded here: the test asserts a one-directional
 * invariant against the real HTMLRewriter (whatever checkSelector accepts,
 * lol-html accepts). Explicit accept/reject expectations live in
 * selector-grammar.test.ts.
 */

/** Selectors a config author might plausibly write, valid or not. */
export const REALISTIC_SELECTORS: string[] = [
  "form",
  "form#contact",
  "form.a.b",
  "form#contact-form",
  "form.wpcf7-form",
  "form.cart",
  'form[action="/contact"]',
  'form[action="/a,b"]',
  "form[action=/contact]",
  "form[action=/de/kontakt/]",
  "form[data-id=123]",
  'form[data-id="123"]',
  "input[name=2fa]",
  'input[name="2fa"]',
  "input[name=email]",
  "input[name=your-name]",
  "textarea[name=message]",
  "input[type=email]",
  "form[name=]",
  "form#123",
  "form.1abc",
  "form.",
  "form#",
  "form:not()",
  "form:not",
  "form:nth-child",
  "form:nth-child()",
  "form:nth-child(foo)",
  "form:nth-child(2n+1 of .a)",
  "form:first-child(x)",
  "form:first-child",
  "form:not(.a)",
  "form:has(input)",
  "form + form",
  "form ~ div",
  "form#a, form#b",
  "form > input",
  "> input",
  "input:hover",
  "main, article, [role=main]",
  "nav",
  "script",
];

/** Contrived and malformed selectors, the kind a denylist forgets. */
export const CONTRIVED_SELECTORS: string[] = [
  "form\\:has(a)",
  "form[a b]",
  'form[a="b" x]',
  "form[ns|a]",
  "svg|rect",
  "*|a",
  "|a",
  "form!",
  "form;",
  "form()",
  'form "x"',
  "form\u000binput",
  'form/*"*/:hover/*"*/',
  "form/*[*/:hover/*]*/",
  "form/*x*/",
  "form /* */ input",
  "form@",
  "form$",
  "form%",
  "form&",
  "form=",
  "form{",
  "form}",
  "form`",
  "form^",
  "form<",
  "form?",
  "form:",
  "form:-x",
  "form.\u2028a",
  "form#a\u2028",
  "form\u00a0input",
  "**",
  "form*",
  "svg:rect",
];

/** Whitespace, attribute, identifier and pseudo-class edge cases from probing lol-html directly. */
export const PROBED_SELECTORS: string[] = [
  " form",
  "form ",
  " form ",
  "form\tinput",
  "form\ninput",
  "form\rinput",
  "form\finput",
  "form >input",
  "form> input",
  "form\t>\tinput",
  "form\n>\ninput",
  "[a]",
  "[ a]",
  "[a ]",
  "[ a ]",
  "[a = b]",
  "[a=b ]",
  "[ a=b]",
  '[a="b"]',
  '[a ="b"]',
  '[a= "b"]',
  '[a="b" ]',
  '[a="b" i]',
  '[a="b" s]',
  '[a="b"i]',
  "[a=b i]",
  "[a=b  i]",
  '[a="b" I]',
  '[a="b" S]',
  '[a="b" i ]',
  '[a="b" i s]',
  '[a="b" x]',
  "[a=b i ]",
  '[a="b"\ti]',
  '[name="q" i]',
  '[name="q" s]',
  '[class~="a"]',
  '[lang|="en"]',
  '[href^="https://"]',
  '[href$=".pdf"]',
  '[href*="x"]',
  "[a~=b]",
  "[a^=b]",
  "[a$=b]",
  "[a*=b]",
  "[a|=b]",
  "[a ~= b]",
  "[a ~ = b]",
  "[a=-b]",
  "[a=_b]",
  "[a=b-1]",
  "[a=1]",
  "[a=-1]",
  "[a=b.c]",
  '[a=""]',
  "[a='']",
  '[a="x y"]',
  '[a="x\ty"]',
  '[a="x\ny"]',
  '[a="x\\y"]',
  '[a="a\\"b"]',
  'form[title="a + b ~ c > d"]',
  "form[title='a, b']",
  '[data-x=":has(a), b + c ~ d > e"]',
  "[data-x='::before']",
  "[data-x]",
  "[_a]",
  "[-a]",
  "[--a]",
  "[a-1]",
  "[1a]",
  "[a.b]",
  "[a:b]",
  "[Ab]",
  "[é]",
  "[a=é]",
  "form#a",
  "form#-a",
  "form#_a",
  "form#--a",
  "form#a-1",
  "form#a1",
  "form#é",
  "form.é",
  "form.-a",
  "form.--a",
  "form._a",
  "form.a-1",
  "form.A.B",
  "form. a",
  "form#a ",
  "h1",
  "a-b",
  "é",
  "*",
  "form *",
  "form  input",
  "form .a #b",
  "*:first-child",
  "*.a",
  "*#a",
  "#a#b",
  ".a.b.c",
  "form:first-child:first-child",
  "form:first-child.a",
  ".a:first-child",
  ":first-child",
  ":FIRST-CHILD",
  ":first-of-type",
  ":first-child()",
  ":first-of-type()",
  ":nth-child(1)",
  ":nth-child(0)",
  ":nth-child(-2)",
  ":nth-child(+2)",
  ":nth-child(n)",
  ":nth-child(-n)",
  ":nth-child(+n)",
  ":nth-child(2n)",
  ":nth-child(2n+1)",
  ":nth-child(2n-1)",
  ":nth-child(2n + 1)",
  ":nth-child(2n +1)",
  ":nth-child(2n+ 1)",
  ":nth-child( 2n+1 )",
  ":nth-child(- n+3)",
  ":nth-child(-n+3)",
  ":nth-child(-n + 3)",
  ":nth-child(+ 2)",
  ":nth-child(odd)",
  ":nth-child(even)",
  ":nth-child(ODD)",
  ":nth-child(Even)",
  ":nth-child(N)",
  ":nth-child(2N+1)",
  ":nth-child(odd of .a)",
  ":nth-child(1.5)",
  ":nth-child(2 n)",
  ":nth-child(2n+)",
  ":nth-child(+)",
  ":nth-child(n+n)",
  "li:nth-child(2n+1)",
  ":nth-of-type(2)",
  ":nth-of-type(2n+1)",
  ":nth-of-type(odd)",
  ":nth-of-type()",
  ":nth-of-type",
  "li:first-of-type",
  "li:nth-of-type(2)",
  ":not(.a)",
  ":not( .a )",
  ":not(.a,.b)",
  ":not(.a , .b)",
  ":not(a b)",
  ":not(a > b)",
  ":not(> a)",
  ":not(a >)",
  ":not(:first-child)",
  ":not(:not(.a))",
  ":not(:not(:not(.a)))",
  ":not(.a",
  ":not(.a))",
  ":not(a, )",
  ":not(, a)",
  ":not(a,,b)",
  ":not(*)",
  ":not([a])",
  ':not("x")',
  ":not(a:hover)",
  ":not(:hover)",
  ":not(:has(a))",
  ":not(a::before)",
  ":not(:nth-child(2n+1))",
  ":not(a, b > c)",
  ":not(a + b)",
  ":not(a ~ b)",
  "div:not(.a, .b)",
  "div:not(a b)",
  "div:not(.a .b)",
  "div:not(div > a)",
  "input:not([type=hidden])",
  "input:not(:first-child)",
  "li:not(:nth-child(2))",
  "li:last-child",
  "input:checked",
  "input:nth-last-child(2)",
  "input:only-child",
  "input:empty",
  "form:is(.a)",
  "a::before",
  "form[a=b",
  "form]",
  "li:nth-child(2",
  "li)",
  "form >",
  "form > > input",
  "form\\#a",
  "form#a\\,b",
  "form.a\\+b",
  "FORM#X",
  "form:FIRST-CHILD",
];

/** Atoms for the generated sweep: well-formed pieces and the characters that break them. */
const ATOMS: string[] = [
  "form", "a", "*", "#a", "#1", ".b", ".", ".1", "[a]", "[a=b]", "[a=1]", '[a="x"]', '[a="x" i]', "[a=", "]", "[", "(", ")",
  ":first-child", ":hover", ":has(", ":not(", ":not(.a)", ":nth-child(", "2n+1", "odd", " of .a", "n", ":", "::", "::before",
  ">", " > ", " ", "  ", "+", "~", ",", ", ", '"', "'", "\\", "/*", "*/", "|", "!", "-", "_", "é", "1", "=", "~=", "|=",
  "\t", "\n", "\u000b", "i", "s", " i", "|a",
  // Uppercase (lol-html refuses an uppercase attribute NAME once an operator follows) and surrogates.
  "A", "B", "[A]", "[A=b]", "[aB=c]", ":NOT(", "\ud800", "\ud83d\ude00", '[a="\ud800"]',
];

/** Deterministic PRNG so the generated sweep is the same on every run. */
function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Every concatenation of up to three atoms, plus a seeded random sample of longer
 * ones. Most are garbage on purpose: the point is that none of the garbage the
 * grammar accepts is refused by lol-html.
 */
export function generatedSelectors(randomCount = 20_000): string[] {
  const out: string[] = [];
  for (const a of ATOMS) {
    out.push(a);
    for (const b of ATOMS) {
      out.push(a + b);
      for (const c of ATOMS) out.push(a + b + c);
    }
  }
  const rand = mulberry32(0xc0ffee);
  for (let n = 0; n < randomCount; n++) {
    const len = 4 + Math.floor(rand() * 5);
    let s = "";
    for (let k = 0; k < len; k++) s += ATOMS[Math.floor(rand() * ATOMS.length)];
    out.push(s);
  }
  return out;
}

/**
 * Uppercase in every position. lol-html takes it in type selectors, ids and classes,
 * and in a bare attribute name (`[A]`), but throws "explicit namespaces" for an
 * uppercase attribute name followed by an operator and value.
 */
export const UPPERCASE_SELECTORS: string[] = [
  "FORM", "Form", "A", "INPUT", "FORM#x", "FORM.x", "FORM > INPUT", "A:NOT(B)", "A:not(B)", "FORM:FIRST-CHILD",
  "form#ID", "form#Id", "form.CLASS", "form.aB.Cd", "#A", ".A", "form#A.B",
  "FORM[name=x]", "form[NAME]", "form[name=X]", "FORM#X[name=y]", "form.A[b=c]", "form#A[b=c]",
  "[A]", "[aB]", "[ACTION]", "form[ACTION]", "[data-X]", "[-A]", "[_A]", "[a-B]",
  "[A=b]", "[aB=c]", "[aB~=c]", "[aB^=c]", "[aB$=c]", "[aB*=c]", "[aB|=c]", "[A|=b]", '[A="b"]', '[aB="c" i]',
  "[a=B]", '[a="B"]', "[a=bC]", "[a=bC i]",
  'form[ACTION="/contact"]', 'form[data-formId="12"]', 'form[METHOD="post" i]', 'input[autoComplete="email"]',
  'input[NAME="email"]', 'input[Name="email"]', "input[TYPE=email]", "INPUT[NAME=EMAIL]",
  "[data-X=y]", "[-A=b]", "[_A=b]", "[a-B=c]", ":not([aB=c])", "[A$=-n\n]",
  "[é=a]", "[É=a]", "[aÉ=b]", "[É]",
];

/** Lone surrogates (reachable from TOML escapes like "\uD800") and valid pairs. */
export const SURROGATE_SELECTORS: string[] = [
  '[a="\ud800"]',
  '[a="\udc00x"]',
  "form.\ud800",
  "form#\ud800",
  '[a="\ud83d\ude00"]',
  "form#\ud83d\ude00",
  "\ud83d\ude00",
];

export const HAND_WRITTEN_CORPUS: string[] = [
  ...new Set([
    ...REALISTIC_SELECTORS,
    ...CONTRIVED_SELECTORS,
    ...PROBED_SELECTORS,
    ...UPPERCASE_SELECTORS,
    ...SURROGATE_SELECTORS,
  ]),
];
