/**
 * cf-webmcp Worker entry.
 *
 * Loads the compiled config (generated by scripts/build-config.ts), matches
 * the request against the route table, and either handles directly or proxies
 * to origin.
 */

import { config, CONFIG_HASH, BOOTSTRAP_ASSET, WIDGET_ASSET } from "./generated/config";
import { BOOTSTRAP_JS as bootstrapJs, LANDING_HTML as landingHtml, MANIFEST_JSON as manifestJson } from "./generated/assets";

import { matchRoute } from "./router";
import { manifestResponse } from "./routes/manifest";
import { landingRedirect, landingResponse } from "./routes/landing";
import { bootstrapResponse } from "./routes/bootstrap";
import { execResponse } from "./routes/exec";
import { healthResponse } from "./routes/health";
import { widgetResponse } from "./routes/widget";
import { llmsTxtResponse } from "./routes/llms-txt";
import { robotsTxtResponse } from "./routes/robots-txt";
import { agentsMdResponse, agentsMdRedirect } from "./routes/agents-md";
import { formsForPath, injectIntoHtml, shouldInject } from "./injection/html-rewriter";

export interface Env {
  CF_WEBMCP_ASSETS: R2Bucket;
  CF_WEBMCP_DEPLOY_TOKEN?: string;
  CF_WEBMCP_HEALTH_TOKEN?: string;
}

const DEPLOYED_AT = new Date().toISOString();

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const match = matchRoute(config, url, BOOTSTRAP_ASSET, WIDGET_ASSET);

    switch (match.kind) {
      case "manifest":
        return handleHeadable(request, manifestResponse(manifestJson, config, CONFIG_HASH));
      case "landing":
        return handleHeadable(request, landingResponse(landingHtml, config, CONFIG_HASH));
      case "landing_redirect":
        return landingRedirect(config.webmcp_landing.path);
      case "bootstrap":
        return handleHeadable(request, bootstrapResponse(bootstrapJs, config));
      case "widget":
        return widgetResponse(request, config, env.CF_WEBMCP_ASSETS, WIDGET_ASSET);
      case "exec":
        return execResponse(
          request,
          config,
          match.toolName!,
          { domain: config.site.domain, deployToken: env.CF_WEBMCP_DEPLOY_TOKEN ?? "" },
          (p) => ctx.waitUntil(p),
        );
      case "health":
        return healthResponse(request, config, {
          configHash: CONFIG_HASH,
          schemaVersion: config.schema_version,
          deployedAt: DEPLOYED_AT,
        });
      case "llms_txt":
        return llmsTxtResponse(request, config, (u) => proxyToOrigin(u, env));
      case "robots_txt":
        return robotsTxtResponse(request, config, (u) => proxyToOrigin(u, env));
      case "agents_md":
        return agentsMdResponse(request, config, (u) => proxyToOrigin(u, env));
      case "agents_md_redirect":
        return agentsMdRedirect(config);
      case "proxy":
        return proxyAndMaybeInject(request, env);
    }
  },
} satisfies ExportedHandler<Env>;

function handleHeadable(request: Request, response: Response): Response {
  if (request.method === "HEAD") {
    return new Response(null, { status: response.status, headers: response.headers });
  }
  return response;
}

async function proxyToOrigin(url: URL, env: Env): Promise<Response> {
  const target = new URL(url.pathname + url.search, config.origin.base_url);
  const headers = new Headers();
  headers.set("user-agent", "cf-webmcp/1.0");
  if (env.CF_WEBMCP_DEPLOY_TOKEN) {
    headers.set("cf-webmcp-bypass", "1");
    headers.set("cf-webmcp-deploy-token", env.CF_WEBMCP_DEPLOY_TOKEN);
  }
  const res = await fetch(target.toString(), { method: "GET", headers, redirect: "follow" });
  // Defense in depth: refuse to relay content from any host outside the
  // configured allow-list, even if origin redirected us there.
  if (res.url) {
    try {
      const finalOrigin = new URL(res.url).origin;
      const allowed = config.origin.allowed_origins.map((u) => new URL(u).origin);
      if (!allowed.includes(finalOrigin)) {
        return new Response(
          `origin redirected to ${finalOrigin} which is not in allowed_origins`,
          { status: 502, headers: { "content-type": "text/plain; charset=utf-8" } },
        );
      }
    } catch {
      return new Response("origin returned malformed final URL", { status: 502 });
    }
  }
  return res;
}

async function proxyAndMaybeInject(request: Request, env: Env): Promise<Response> {
  const reqUrl = new URL(request.url);
  const target = new URL(reqUrl.pathname + reqUrl.search, config.origin.base_url);

  // redirect:"manual" - pass any 3xx response back to the visitor's browser
  // unchanged instead of auto-following. Auto-following would mean the worker
  // injects the bootstrapper into the FINAL response, even if origin redirected
  // off-host. The visitor's browser handles redirect chains natively; we just
  // relay them.
  const upstream = await fetch(target.toString(), new Request(request, { redirect: "manual" }));

  if (!config.features.inject_html) return upstream;
  if (!shouldInject(request, upstream, config)) return withLinkHeader(upstream);

  const manifestUrl = `${config.site.public_url ?? `https://${config.site.domain}`}${config.manifest.path}`;
  const bootstrapUrl = `${config.site.public_url ?? `https://${config.site.domain}`}${config.paths.namespace}/${BOOTSTRAP_ASSET}`;
  const forms = formsForPath(config.forms, reqUrl.pathname);
  const injected = injectIntoHtml(upstream, {
    manifestUrl,
    bootstrapUrl,
    emitLinkTag: config.features.link_tag,
    forms,
  });
  return withLinkHeader(injected);
}

function withLinkHeader(response: Response): Response {
  if (!config.features.link_header) return response;
  const manifestUrl = `${config.site.public_url ?? `https://${config.site.domain}`}${config.manifest.path}`;
  const headers = new Headers(response.headers);
  const existing = headers.get("link");
  const value = `<${manifestUrl}>; rel="webmcp"`;
  headers.set("link", existing ? `${existing}, ${value}` : value);
  return new Response(response.body, { status: response.status, headers });
}
