/**
 * cf-webmcp Worker entry.
 *
 * Wiring only: loads the compiled config and assets generated by
 * scripts/build-config.ts and hands them to createHandler() (src/handler.ts),
 * which holds all request logic.
 */

import {
  config,
  CONFIG_HASH,
  MANIFEST_ETAG,
  LANDING_ETAG,
  ARD_ETAG,
  INJECTION_HASH,
  BOOTSTRAP_ASSET,
  WIDGET_ASSET,
  BUILD_AT,
  PREFLIGHT,
  AGENT_SKILLS_DIGEST,
  BOOTSTRAP_SRI,
  LLMS_TXT_TOKEN_HINTS,
} from "./generated/config";
import {
  BOOTSTRAP_JS,
  LANDING_HTML,
  MANIFEST_JSON,
  AI_CATALOG_JSON,
} from "./generated/assets";
import { createHandler } from "./handler";

export default createHandler({
  config,
  assets: {
    bootstrapJs: BOOTSTRAP_JS,
    landingHtml: LANDING_HTML,
    manifestJson: MANIFEST_JSON,
    aiCatalogJson: AI_CATALOG_JSON,
  },
  meta: {
    CONFIG_HASH,
    MANIFEST_ETAG,
    LANDING_ETAG,
    ARD_ETAG,
    INJECTION_HASH,
    BOOTSTRAP_ASSET,
    WIDGET_ASSET,
    BUILD_AT,
    PREFLIGHT,
    AGENT_SKILLS_DIGEST,
    BOOTSTRAP_SRI,
    LLMS_TXT_TOKEN_HINTS,
  },
});
